---
title: "Circos Graphs for the 5 Counties in NYC"
author: "Yaran Fan"
date: "March 22, 2016"
output: html_document
---

```{r, include = FALSE}
if (!require("circlize")) install.packages("circlize")
library("circlize")
library("RColorBrewer")

setwd("C:/Users/hongzhili/Google Drive/2016 Spring/W4701 Exploratory Data Analysis and Visualization/HW3")


# Read in all files
  # Age and Gender
  age_gender = read.csv("Data/NYC_age_gender.csv", row.names=1)
  
  # Education
  education = read.csv("Data/NYC_education.csv", row.names=1)
  
  # Income
  income = read.csv("Data/NYC_income.csv", row.names=1)
  
  # Race
  race = read.csv("Data/NYC_race.csv", row.names=1)
  
  # Cash rent
  rent_cash = read.csv("Data/NYC_rent.csv", row.names=1)

```

###Age and Gender
```{r,echo=FALSE, fig.width=6, fig.height=6}  
  # county colors
  c2 = c("#8dd03d", "#6b62f2", "#41bbf2", "#efbd26", "#f95959")
  
  # Age and Gender
  data = as.matrix(age_gender)
  colnames(data) = sub("X_","",colnames(data))
  colnames(data) = sub(".1",".",colnames(data))
  colnames(data) = sub("plus","+",colnames(data))
  c11 = brewer.pal(9,"Blues")[2:9]
  c12 = brewer.pal(9,"OrRd")[2:9]
  grid.col = NULL
  grid.col[c(colnames(data),rownames(data))] = c(c11, c12, c2)
  chordDiagram(data, grid.col = grid.col)
```

###Education
```{r,echo=FALSE, fig.width=6, fig.height=6}  
  # Education
  data = as.matrix(education)
  colnames(data) = sub("Less_than_","<",colnames(data))
  colnames(data) = sub("_to_","-",colnames(data))
  c1 = rev(gray.colors(ncol(data)))
  grid.col = NULL
  grid.col[c(colnames(data),rownames(data))] = c(c1, c2)
  chordDiagram(data, grid.col = grid.col)
```

###Income
```{r,echo=FALSE, fig.width=6, fig.height=6}  
  # Income
  data = as.matrix(income)
  colnames(data) = sub("USD_","$",colnames(data))
  colnames(data) = sub("_to_","-$",colnames(data))
  colnames(data) = sub("Less_than_","<$",colnames(data))
  colnames(data) = sub("Over_200K","$200K+",colnames(data))
  c1 = rev(gray.colors(ncol(data)))
  grid.col = NULL
  grid.col[c(colnames(data),rownames(data))] = c(c1, c2)
  chordDiagram(data, grid.col = grid.col)
```

###Race
```{r,echo=FALSE, fig.width=6, fig.height=6}  
  # Race
  data = as.matrix(race)
  colnames(data) = sub("X_2._","2+ ",colnames(data))
  c1 = rev(gray.colors(ncol(data)))
  grid.col = NULL
  grid.col[c(colnames(data),rownames(data))] = c(c1, c2)
  chordDiagram(data, grid.col = grid.col)
```

###Cash Rent
```{r,echo=FALSE, fig.width=6, fig.height=6}  
  # Cash rent
  data = as.matrix(rent_cash)
  colnames(data) = sub("USD_","$",colnames(data))
  colnames(data) = sub("_to_","-$",colnames(data))
  colnames(data) = sub("Less_than_","<$",colnames(data))
  colnames(data) = sub("_or_more","+",colnames(data))
  c1 = rev(gray.colors(ncol(data)))
  grid.col = NULL
  grid.col[c(colnames(data),rownames(data))] = c(c1, c2)
  chordDiagram(data, grid.col = grid.col)
```